### ISSUE TITLE
Studying content, conflict bug with single site local value

### ISSUE THREAD

**Issue by huguespages** [my-language-skills/simple-metadata-education#17]
<!-- Please use this template when creating an issue.

* [ x] I've read and understood the [contribution guidelines](https://github.com/my-language-skills/aiom-educational-related-content/blob/master/.github/CONTRIBUTING.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
When you said local value in multisite admin, we have a bug
![image](https://user-images.githubusercontent.com/49389319/62877283-fba7dd00-bd26-11e9-822a-6cc98bfed62c.png)

### Please describe what you expected to happen and why.
We expected to have the same with other field

**Comment by lukastonhajzer** [comment]
Fixed by running smde_update_network_options() function on 'network_admin_edit_smde_update_network_for_lang' hook. So network table (and $network_props_class variable in smde-admin-settings.php) is automatically updated with the new fields and  which are changed by activating and deactivating 'Content is for languages education' checkbox.
Fix creates new minor issue #18
